### ISSUE TITLE
[bug]vue3添加路由动画后swiper出现错误

### ISSUE THREAD

**Issue by nyrf** [jdf2e/nutui#1245]
## 问题描述
vue3添加路由动画后, 跳转到有swiper的页面会出现错误

```
0 2
nutui.es.js:1670 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'getBoundingClientRect')
    at init (nutui.es.js:1670:36)
    at nutui.es.js:1759:9
```

## 最小可复现仓库

```vue
<template>
  <router-view class="router-view" v-slot="{ Component }">
    <transition name="slide-left" mode="out-in">
      <component :is="Component" />
    </transition>
  </router-view>
<router-link to="/">首页</router-link>
<router-link to="/login">登录</router-link>
</template>
<script setup>
</script>

<style>
.router-view {
  width: 100vw;
  height: 100vh;
  position: absolute;
  top: 0;
  bottom: 0;
  margin: 0 auto;
  overflow-y: auto;
  overflow-x: hidden;
  -webkit-overflow-scrolling: touch;
}

.slide-right-enter-active,
.slide-right-leave-active,
.slide-left-enter-active,
.slide-left-leave-active {
  will-change: transform;
  transition: all 500ms;
  position: absolute;
}

.slide-right-enter {
  opacity: 0;
  transform: translate3d(-100%, 0, 0);
}

.slide-right-leave-active {
  opacity: 0;
  transform: translate3d(100%, 0, 0);
}

.slide-left-enter {
  opacity: 0;
  transform: translate3d(100%, 0, 0);
}

.slide-left-leave-active {
  opacity: 0;
  transform: translate3d(-100%, 0, 0);
}
</style>

```

Home.vue

```vue
<template>
  <nut-swiper
    :init-page="page4"
    :loop="true"
    auto-play="3000"
    direction="vertical"
    height="150"
    :pagination-visible="true"
    style="height: 150px"
  >
    <nut-swiper-item>
      <img
        src="https://storage.360buyimg.com/jdc-article/NutUItaro34.jpg"
        alt=""
      />
    </nut-swiper-item>
    <nut-swiper-item>
      <img
        src="https://storage.360buyimg.com/jdc-article/NutUItaro2.jpg"
        alt=""
      />
    </nut-swiper-item>
    <nut-swiper-item>
      <img
        src="https://storage.360buyimg.com/jdc-article/welcomenutui.jpg"
        alt=""
      />
    </nut-swiper-item>
    <nut-swiper-item>
      <img
        src="https://storage.360buyimg.com/jdc-article/fristfabu.jpg"
        alt=""
      />
    </nut-swiper-item>
  </nut-swiper>
</template>
<script lang="ts">
import { reactive, toRefs } from 'vue'
export default {
  setup() {
    const state = reactive({
      page4: 0
    })
    return { ...toRefs(state) }
  }
}
</script>
<style lang="scss" scoped>
.nut-swiper-item {
  line-height: 150px;
  img {
    width: 100%;
    height: 100%;
  }
}
</style>

```

## 相关环境信息
- **操作系统**：macOS 12.3.1 (21E258)
- **Node 版本**：17
- **NutUI 版本**： @nutui/nutui@3.1.18
- **Vue 版本**：3.2.25
- **引用方式**：  NPM ？

**Comment by szg2008** [comment]
5.30发布新版本后再试一下
