### ISSUE TITLE
用taro升级nutui到3.1.20后运行就失败了 [bug]

### ISSUE THREAD

**Issue by suguer** [jdf2e/nutui#1271]
## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 复现步骤，具体代码

原来是3.1.8版本 yarn upgrade 后,我的taro就运行失败了,.提示
```
./node_modules/@nutui/nutui-taro/dist/packages/col/index.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Undefined operation "calc(100 / 24) * 1".
    ╷
110 │     margin-left: calc(100 / 24) * $i * 1%;
    │                  ^^^^^^^^^^^^^^^^^^^
    ╵
  node_modules\@nutui\nutui-taro\dist\packages\col\index.scss 110:18  root stylesheet
    at K:\Web\rent3\node_modules\webpack\lib\NormalModule.js:316:20
    at K:\Web\rent3\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at K:\Web\rent3\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (K:\Web\rent3\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at K:\Web\rent3\node_modules\sass-loader\dist\index.js:62:7
    at Function.call$2 (K:\Web\rent3\node_modules\sass\sass.dart.js:92571:16)
    at _render_closure1.call$2 (K:\Web\rent3\node_modules\sass\sass.dart.js:81074:12)
    at _RootZone.runBinary$3$3 (K:\Web\rent3\node_modules\sass\sass.dart.js:27256:18)
    at _FutureListener.handleError$1 (K:\Web\rent3\node_modules\sass\sass.dart.js:25812:19)
    at _Future__propagateToListeners_handleError.call$0 (K:\Web\rent3\node_modules\sass\sass.dart.js:26110:49)
    at Object._Future__propagateToListeners (K:\Web\rent3\node_modules\sass\sass.dart.js:4536:77)
    at _Future._completeError$2 (K:\Web\rent3\node_modules\sass\sass.dart.js:25942:9)
    at _AsyncAwaitCompleter.completeError$2 (K:\Web\rent3\node_modules\sass\sass.dart.js:25596:12)
    at Object._asyncRethrow (K:\Web\rent3\node_modules\sass\sass.dart.js:4335:17)
    at K:\Web\rent3\node_modules\sass\sass.dart.js:12852:20
    at _wrapJsFunctionForAsync_closure.$protected (K:\Web\rent3\node_modules\sass\sass.dart.js:4360:15)
 @ ./src/app.ts (./node_modules/babel-loader/lib!./src/app.ts) 11:0-56
 @ ./src/app.ts


node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "[object Array]".] {
  code: 'ERR_UNHANDLED_REJECTION'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

## 相关环境信息
- **操作系统**： window
- **Node 版本**：14
- **NutUI 版本**： @nutui/nutui@3.1.20
- **Vue 版本**：3
- **引用方式**：  yarn

**Comment by EricPengLong** [comment]
我也报这个错

**Comment by suguer** [comment]
我回退版本就好了,应该是新版本不兼容

**Comment by richard1015** [comment]
升级taro 3.4.x  即可解决 ,由于taro 内部升级了sass 1.50以上的版本

**Comment by suguer** [comment]
> 升级taro 3.4.x 即可解决 ,由于taro 内部升级了sass 1.50以上的版本

我的taro是3.4.4的

**Comment by jaqen404** [comment]
我也是，回退到v3.1.18就可以了

**Comment by oneheartyang** [comment]
请问你是回退的taro 版本还是 nutui/nutui 还是 nutui/nutui-taro

**Comment by jaqen404** [comment]
> 请问你是回退的 taro (芋头) 版本还是 nutui/nutui 还是 nutui/nutui-taro

@nutui/nutui-taro   v3.1.18

**Comment by oneheartyang** [comment]
> nutui
 "dependencies": {
  "@nutui/nutui-taro": "^3.1.18",
  "@tarojs/plugin-framework-vue3": "^3.4.11",
}
运行命令：yarn dev:h5
Taro v3.4.11

🙅   Failed to compile.

./node_modules/@nutui/nutui-taro/dist/styles/themes/default.scss)
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Undefined operation "calc(100 / 24) * 1".
   ╷
18 │     margin-left: calc(100 / 24) * $i * 1%;
   │                  ^^^^^^^^^^^^^^^^^^^
   ╵
  node_modules\@nutui\nutui-taro\dist\packages\col\index.scss 18:18    @import
  node_modules\@nutui\nutui-taro\dist\styles\themes\default.scss 45:9  root stylesheet

是版本哪里没对上么

**Comment by JakeWoki** [comment]
```
./node_modules/@nutui/nutui-taro/dist/packages/col/index.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Undefined operation "calc(100 / 24) * 1".
   ╷
19 │     margin-left: calc(100 / 24) * $i * 1%;
   │                  ^^^^^^^^^^^^^^^^^^^
   ╵
  node_modules\@nutui\nutui-taro\dist\packages\col\index.scss 19:18  root stylesheet
```

@richard1015 
@nutui/nutui-taro v3.1.22
Taro v3.4.3
这样仍然有问题，3.1.17也不行，去掉Layout 布局的Col的引用就正常

改成
@nutui/nutui-taro v3.1.22
Taro v3.4.13可以了

**Comment by jackzhujie** [comment]
同样遇到该问题，只能去掉col组件了
