### ISSUE TITLE
[bug]3.2.1List组件在taro3.2+webpack5下报错

### ISSUE THREAD

**Issue by kongsiyu** [jdf2e/nutui#1549]
## 问题描述
[bug]3.2.1List组件在taro3.2+webpack5下报错
···
List.js?63f4:26 
        
       Uncaught (in promise) TypeError: _tarojs_taro__WEBPACK_IMPORTED_MODULE_2___default(...).getSystemInfoSync is not a function
    at eval (List.js?63f4:26:1)
    at ./node_modules/@nutui/nutui-taro/dist/packages/_es/List.js (src_app_boot_js.js:40:1)
    at __webpack_require__ (runtime.js:36:33)
    at fn (runtime.js:452:21)
    at eval (app.ts:10:97)
    at ./src/app.ts (src_app_boot_js.js:683:1)
    at __webpack_require__ (runtime.js:36:33)
    at fn (runtime.js:452:21)
    at eval (app.boot.js:6:62)
    at ./src/app.boot.js (src_app_boot_js.js:672:1)
···

## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库
https://github.com/kongsiyu/nutui_taro35_webpack5.git)
## 复现步骤，具体代码

app.ts
```
// 只需要在taro-nutui template项目新增List引用就可重现
App.use(Button).use(Toast).use(List)
```

## 相关环境信息
- **操作系统**：
- **Node 版本**：
- **NutUI 版本**： 查看项目package.json 中 @nutui/* 信息
- **Vue 版本**：
- **引用方式**：  NPM

**Comment by kongsiyu** [comment]
在小程序下Button也会报错
```
VM3005:9 app.js错误:
 TypeError: __webpack_modules__[moduleId] is not a function
    at __webpack_require__ (webpack_bootstrap:19)
    at Object../node_modules/@nutui/nutui-taro/dist/packages/_es/Button.js (._node_modules_@nutui_nutui-taro_dist_packages__es_Avatar.js:168)
    at __webpack_require__ (webpack_bootstrap:19)
    at Object../node_modules/babel-loader/lib/index.js??clonedRuleSet-11.use[0]!./src/app.ts (._node_modules_@nutui_nutui-taro_dist_packages_locale_lang_zh-CN.js:7)
    at __webpack_require__ (webpack_bootstrap:19)
    at Object../src/app.ts (._src_app.ts:107)
    at __webpack_require__ (webpack_bootstrap:19)
    at __webpack_exec__ (._node_modules_@babel_runtime_helpers_esm_unsupportedIterableToArray.js:9)
    at ._node_modules_@babel_runtime_helpers_esm_unsupportedIterableToArray.js:9
    at Function.__webpack_require__.O (webpack_runtime_chunk loaded:25)(env: Windows,mp,1.06.2208010; lib: 2.25.1)
```

**Comment by kongsiyu** [comment]
奇怪，就我一个人遇到这个问题？

**Comment by kongsiyu** [comment]
另外备注一下，你们版本号写错了
![image](https://user-images.githubusercontent.com/8521224/184283951-ec98bd98-c348-4ad1-a259-2feba5db573e.png)

**Comment by shaibaoj** [comment]
我也遇到了

**Comment by kongsiyu** [comment]
> 我也遇到了

解决了吗

**Comment by kongsiyu** [comment]
@szg2008 啥情况啊大佬，有没有解决方案

**Comment by droplet-js** [comment]
啥情况啊，昨天还好好的，今天就跪了

**Comment by kongsiyu** [comment]
> 啥情况啊，昨天还好好的，今天就跪了

发版开始就一直这样的，只要用webpack5，我都提了快1个月了都没人管
我现在解决方案就是退回3.2.0，然后关闭prebundle
```
prebundle: {
  enable: false
}
````

**Comment by droplet-js** [comment]
> > 啥情况啊，昨天还好好的，今天就跪了
> 
> 发版开始就一直这样的，只要用webpack5，我都提了快1个月了都没人管 我现在解决方案就是退回3.2.0，然后关闭prebundle
> 
> ```
> prebundle: {
>   enable: false
> }
> ```

thanks

**Comment by lwp2333** [comment]
我也遇到了这个问题， List 组件的 props height 默认值 使用了 Taro.getSystemInfo().height ，然后因为默认prebundle  enable true 的原因，好像 @tarojs/api 打包引入在组件之后还是啥原因，就找不到 getSystemInfo 方法报错了

**Comment by xiaosu2016** [comment]
我也出现了这个问题

**Comment by szg2008** [comment]
> 在小程序下Button也会报错
> 
> ```
> VM3005:9 app.js错误:
>  TypeError: __webpack_modules__[moduleId] is not a function
>     at __webpack_require__ (webpack_bootstrap:19)
>     at Object../node_modules/@nutui/nutui-taro/dist/packages/_es/Button.js (._node_modules_@nutui_nutui-taro_dist_packages__es_Avatar.js:168)
>     at __webpack_require__ (webpack_bootstrap:19)
>     at Object../node_modules/babel-loader/lib/index.js??clonedRuleSet-11.use[0]!./src/app.ts (._node_modules_@nutui_nutui-taro_dist_packages_locale_lang_zh-CN.js:7)
>     at __webpack_require__ (webpack_bootstrap:19)
>     at Object../src/app.ts (._src_app.ts:107)
>     at __webpack_require__ (webpack_bootstrap:19)
>     at __webpack_exec__ (._node_modules_@babel_runtime_helpers_esm_unsupportedIterableToArray.js:9)
>     at ._node_modules_@babel_runtime_helpers_esm_unsupportedIterableToArray.js:9
>     at Function.__webpack_require__.O (webpack_runtime_chunk loaded:25)(env: Windows,mp,1.06.2208010; lib: 2.25.1)
> ```

使用上面提供的仓库，重新安装了Taro3.5.6和webpack5.没有复现上面的问题，麻烦重新安装试试，如有问题，我们再看看，🙏反馈

**Comment by momodexuyuan** [comment]
3.5.7一样有问题，直接不用List组件解决。

**Comment by w3cpress** [comment]
检查项目工程使用的taro版本 和 本地环境安装的版本， 只要是一致的就不会报错了。。。也不用回退什么webpack5和Taro的版本，如果不一致开发模式在微信开发者工具就会报错。。。。如果是其他问题就不知道了😄
