### ISSUE TITLE
[bug] 小程序版本picker，开启3d效果，报错，而且向下滑动，直接就定位到第一个元素，版本3.2.2

### ISSUE THREAD

**Issue by lingdulib** [jdf2e/nutui#1653]
## 最小可复现仓库
> 请创建最小可复现代码，并上传到你的 GitHub 仓库

## 复现步骤，具体代码
  <nut-picker
      v-model:visible="voucherShow"
      :columns="voucherTypeArr"
      title="类型"
      @confirm="confirmVoucher"
    />

报错:
TypeError: Cannot read properties of null (reading 'style')
    at Object.getComputedStyle (taro.js:2:1)
    at Proxy.onTouchStart (app.js:2:1)
    at Object.onTouchstart.t.<computed>.t.<computed> (app.js:2:1)
    at callWithErrorHandling (vendors.js:2:1)
    at callWithAsyncErrorHandling (vendors.js:2:1)
    at TaroElement.invoker (vendors.js:2:1)
    at TaroElement.handler (taro.js:2:1)
    at TaroElement.dispatchEvent (taro.js:2:1)
    at dispatch (taro.js:2:1)
    at Object.eventHandler [as eh] (taro.js:2:1)

## 相关环境信息
- **操作系统**：
- **Node 版本**：
- **NutUI 版本**：3.2.2
- **Vue 版本**：3.2
- **引用方式**：  NPM

**Comment by yangxiaolu1993** [comment]
问题已经修改，可先试用 NutUI-Taro 3.2.3-beta.0  进行修改，此版本依赖 Taro 3.5.6
