### ISSUE TITLE
@nutui/nutui-taro在taro的h5开发环境下，滑块step点击无效并报错

### ISSUE THREAD

**Issue by zhuxiaoweb** [jdf2e/nutui#1903]
### NutUI scenes（nutui 场景）
H5（@nutui/nutui）

### NutUI-vue version（nutui-vue 版本）

3.3.0

### Vue version（vue 版本）
3.2.45

### Operating environment（运行环境）
dev:h5

### Citation method（引用方式）
npm

### Node version（node 版本）
18.12.1

### Browser and its version（浏览器及其版本）
108.0.5359.71

### System and its version（系统及其版本）
MacOs 12.5 (21G72)

### Reproduction link（重现）
![screenshot-20221205-094904](https://user-images.githubusercontent.com/32625924/205532575-8fee4651-7ae6-4f7f-9447-a55877928806.png)

Range.js?3b6e:206 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '0')
    at _callee$ (Range.js?3b6e:206:1)
    at tryCatch (vendors-node_modules_taro_h5_prebundle_chunk-SXIJWM4W_js.js:11968:17)
    at Generator.<anonymous> (vendors-node_modules_taro_h5_prebundle_chunk-SXIJWM4W_js.js:12049:22)
    at Generator.next (vendors-node_modules_taro_h5_prebundle_chunk-SXIJWM4W_js.js:11993:21)
    at asyncGeneratorStep (asyncToGenerator.js?b8cc:3:1)
    at _next (asyncToGenerator.js?b8cc:22:1)

### Steps to reproduce（重现步骤）
@nutui/nutui-taro在taro的h5开发环境下，滑块step点击无效还会报错

### What is expected?（期望的结果是什么？）
期望滑块点击正常、不报错

### What is actually happening?（实际的结果是什么？）
期望滑块点击无效、报错

**Comment by zhuxiaoweb** [comment]
有人吗
