### ISSUE TITLE
NutUI4，在脚手架选择Vue3时，提示找不到依赖 "@tarojs/plugin-framework-react"

### ISSUE THREAD

**Issue by YI--** [jdf2e/nutui#2145]
### NutUI scenes（nutui 场景）
小程序（@nutui/nutui-taro）

### NutUI-vue version（nutui-vue 版本）

4.0.2

### Vue version（vue 版本）
3.3.0-alpha.4

### Operating environment（运行环境）
dev:weapp

### Citation method（引用方式）
npm

### Node version（node 版本）
16.10.0

### Browser and its version（浏览器及其版本）
Chrome(版本 109.0.5414.119)

### System and its version（系统及其版本）
MacOS 12.6.3

### Taro environmental information（taro 环境信息）
```
  Taro CLI 3.6.2 environment info:
    System:
      OS: macOS 12.6.3
      Shell: 5.8.1 - /bin/zsh
    Binaries:
      Node: 16.10.0 - ~/.nvm/versions/node/v16.10.0/bin/node
      Yarn: 1.22.19 - /usr/local/bin/yarn
      npm: 7.24.0 - ~/.nvm/versions/node/v16.10.0/bin/npm
    npmPackages:
      @tarojs/cli: 3.6.2 => 3.6.2 
      @tarojs/components: 3.6.2 => 3.6.2 
      @tarojs/helper: 3.6.2 => 3.6.2 
      @tarojs/plugin-framework-vue3: 3.6.2 => 3.6.2 
      @tarojs/plugin-html: 3.6.2 => 3.6.2 
      @tarojs/plugin-platform-alipay: 3.6.2 => 3.6.2 
      @tarojs/plugin-platform-h5: 3.6.2 => 3.6.2 
      @tarojs/plugin-platform-jd: 3.6.2 => 3.6.2 
      @tarojs/plugin-platform-qq: 3.6.2 => 3.6.2 
      @tarojs/plugin-platform-swan: 3.6.2 => 3.6.2 
      @tarojs/plugin-platform-tt: 3.6.2 => 3.6.2 
      @tarojs/plugin-platform-weapp: 3.6.2 => 3.6.2 
      @tarojs/runtime: 3.6.2 => 3.6.2 
      @tarojs/shared: 3.6.2 => 3.6.2 
      @tarojs/taro: 3.6.2 => 3.6.2 
      @tarojs/webpack5-runner: 3.6.2 => 3.6.2 
      babel-preset-taro: 3.6.2 => 3.6.2 
      eslint-config-taro: 3.6.2 => 3.6.2 

```

### Reproduction link（重现链接）
[nutui.jd.com/taro/vue/4x/](https://nutui.jd.com/taro/vue/4x/#/zh-CN/guide/start)
[demo](https://github.com/YI--/test-taro.git)

### Steps to reproduce（重现步骤）
此链接为官方指南，依据官方教程-使用脚手架安装，其中包管理器选择 yarn，模板选择NutUI4
```

? 请输入项目介绍 
? 请选择框架 Vue3
? 是否需要使用 TypeScript ？ Yes
? 请选择 CSS 预处理器（Sass/Less/Stylus） Sass
? 请选择编译工具 Webpack5
? 请选择包管理工具 yarn
? 请选择模板源 Github（最新）
✔ 拉取远程模板仓库成功！
? 请选择模板 vue3-NutUI4（使用 NutUI4.0 的模板）
```

------
有在群里咨询过，其他人也存在此问题，如果是选择NutUI3的情况下，是可以正常编译的。

### What is expected?（期望的结果是什么？）
期望在按照官方指引安装时，能得到正确的运行。

### What is actually happening?（实际的结果是什么？）
脚手架选择的Vue3 ，NutUI4；
yarn dev:h5 或者其他 提示：
```

{ Error: Cannot find module 'unplugin-vue-components/webpack'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/xxx/xxx/test_taro/myApp/config/index.js:5:53)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Module._compile (/Users/xxx/xxx/test_taro/myApp/node_modules/pirates/lib/index.js:136:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Object.newLoader [as .js] (/Users/xxx/xxx/test_taro/myApp/node_modules/pirates/lib/index.js:141:7)
    at Module.load (internal/modules/cjs/loader.js:600:32) code: 'MODULE_NOT_FOUND' }
找不到依赖 "@tarojs/plugin-framework-react"，请先在项目中安装
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by YI--** [comment]
已提供 最小化[demo](https://github.com/YI--/test-taro.git)

**Comment by eiinu** [comment]
代码中引入第三方插件的语句报错，`Cannot find module`，可能与 node 环境有关
