### ISSUE TITLE
使用 NutUI 模板创建项目，启动 h5 报错

### ISSUE THREAD

**Issue by yunxi177** [jdf2e/nutui#2373]
### NutUI scenes（nutui 场景）
H5（@nutui/nutui）

### NutUI-vue version（nutui-vue 版本）

4.0.10

### Vue version（vue 版本）
3.3.4

### Operating environment（运行环境）
dev:h5

### Citation method（引用方式）
npm

### Node version（node 版本）
16.17.0

### Browser and its version（浏览器及其版本）
chrome

### System and its version（系统及其版本）
Windows

### Reproduction link（重现链接）
[nutui.jd.com/taro/vue/4x/](https://nutui.jd.com/taro/vue/4x/#/zh-CN/guide/start)

### Steps to reproduce（重现步骤）
执行 pnpm dev:h5 出现如下报错：
\.pnpm\webpack@5.69.0_@swc+core@1.3.66\node_modules\webpack\lib\util\hash\wasm-hash.js:108
                const length = data.length;
                                    ^

TypeError: Cannot read properties of undefined (reading 'length')
    at WasmHash._updateWithBuffer (\.pnpm\webpack@5.69.0_@swc+core@1.3.66\node_modules\webpack\lib\util\hash\wasm-hash.js:108:23)
    at WasmHash.update (\.pnpm\webpack@5.69.0_@swc+core@1.3.66\node_modules\webpack\lib\util\hash\wasm-hash.js:51:8)
    at BatchedHash.update (\.pnpm\webpack@5.69.0_@swc+core@1.3.66\node_modules\webpack\lib\util\hash\BatchedHash.js:50:14)
    at NormalModule.updateHash (\.pnpm\webpack@5.69.0_@swc+core@1.3.66\node_modules\webpack\lib\NormalModule.js:1353:8)
    at Compilation._createModuleHash (\.pnpm\webpack@5.69.0_@swc+core@1.3.66\node_modules\webpack\lib\Compilation.js:3936:10)
    at Compilation.createModuleHashes (\.pnpm\webpack@5.69.0_@swc+core@1.3.66\node_modules\webpack\lib\Compilation.js:3903:25)
    at \.pnpm\webpack@5.69.0_@swc+core@1.3.66\node_modules\webpack\lib\Compilation.js:3010:11
    at Hook.eval [as callAsync] (eval at create (\.pnpm\tapable@2.2.1\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:10:1)   
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (\.pnpm\tapable@2.2.1\node_modules\tapable\lib\Hook.js:18:14)
    at \.pnpm\webpack@5.69.0_@swc+core@1.3.66\node_modules\webpack\lib\Compilation.js:2966:36
 ELIFECYCLE  Command failed with exit code 1.

### What is expected?（期望的结果是什么？）
正确运行

### What is actually happening?（实际的结果是什么？）
报错

**Comment by eiinu** [comment]
swc 相关的报错是在 Taro 版本低于 3.6.3 会出现的问题，建议升级 Taro 至最新版本 3.6.8

**Comment by yunxi177** [comment]
> swc 相关的报错是在 Taro 版本低于 3.6.3 会出现的问题，建议升级 Taro 至最新版本 3.6.8

升级后可以了，感谢您的帮助
